# Generated by Django 4.2.1 on 2023-05-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_database_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='end_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='impact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='insight',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='pestle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='published',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='relevance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='start_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
