# Generated by Django 4.2.1 on 2023-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_database_added_alter_database_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='intensity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
