# Generated by Django 4.2.1 on 2023-05-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_database_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='intensity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='likelihood',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='relevance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
