# Generated by Django 4.2.1 on 2023-05-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_database_intensity_alter_database_likelihood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='added',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
