# Generated by Django 4.2.1 on 2023-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_database_sector_alter_database_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
